### ISSUE TITLE
Add TailwindDoorAlreadyInStateError for more precise exception handling

### ISSUE THREAD

**Issue by cayossarian** [frenck/python-gotailwind#297]
# Problem/Motivation

> (Why the issue was filed)
HA Tailwind component Issue [#119329](https://github.com/home-assistant/core/issues/119329) seeks to resolve unnecessary exceptions in the log when automations, for example, may close a door that is already closed and no other error condition is encountered.  

## Expected behavior

> (What you expected to happen)
In order to cleanly differentiate the "state already in requested state" a consumer of this package would either need to check the message string (fragile approach) or catch a specific exception (robust).

## Actual behavior

> (What actually happened)
This package uses TailwindDoorOperationError exception as a base class for other exceptions like disabled and locked conditions and also raises TailwindDoorOperationError itself when the door is already in a requested state, i.e., close or open operation on already closed or open door.

## Steps to reproduce

> (How can someone else make/see it happen)
Call open or close service on closed or open cover respectively.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I propose to add a specific exception for the aforementioned state issue that derives from TailwindDoorOperationError.  This approach is backward compatible.

**Comment by frenck** [comment]
closed in #298
